name: checkov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run checkov
        uses: workivate/actions-template/composite/checkov@v1.8.1
        with:
          directory: .
          checkov_version: 2.3.72
          skip_check: CKV_SECRET_6,CKV2_GHA_1
